version: '3.4'
services:
  placewhatever:
    image: placewhatever
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080/tcp
    volumes:
      - ./.imagerepo:/var/imagerepo:ro
